# Generated by Django 5.0.7 on 2024-07-28 22:36

import django.db.models.deletion
import menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_plato_menu_menu_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='plato',
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=150, validators=[menu.validators.validar_nombre_plato]),
        ),
        migrations.CreateModel(
            name='PlatoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=2)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto')),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='productos',
            field=models.ManyToManyField(through='menu.PlatoProducto', to='menu.producto'),
        ),
    ]
